name: setlist
description: A new Flutter application.

environment:

dependencies:
  rxdart: ^0.16.0+2
  scoped_model: ^0.2.0
  flutter_redux: ^0.5.0
  flutter_list_drag_and_drop: ^0.1.2
  http: ^0.11.3+16
  shared_preferences: ^0.4.1
#  firebase_database: ^0.4.4
#  firebase_core: any
#  cloud_firestore: ^0.7.2
  firebase_auth: ^0.5.5
  google_sign_in: ^3.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Rubik Bold
      fonts:
       - asset: fonts/Rubik-Bold.ttf
    - family: Rubik Medium
      fonts:
       - asset: fonts/Rubik-Medium.ttf
    - family: Rubik Light
      fonts:
       - asset: fonts/Rubik-Light.ttf
    - family: Rubik Regular
      fonts:
       - asset: fonts/Rubik-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
